---
- name: python defaults
  ansible.builtin.blockinfile:
     path: /usr/bin/python
     block: | 
      ansible_python_interpreter=/usr/bin/python3

- name: subscription-manager refresh
  command: subscription-manager refresh

- name: install iptables-services
  command: yum install -y iptables-services

- name: edit /etc/sysconfig/network/
  ansible.builtin.blockinfile:
     path: /etc/sysconfig/network
     block: |
      GATEWAY=192.168.4.22

- name: edit ens224
  blockinfile:
    dest:  /etc/sysconfig/network-scripts/ifcfg-ens224
    block: |
      GATEWAY=192.168.4.22
    insertafter: EOF
    create: yes

- name: Flush tables
  command: "iptables -F"

- name: Flush nat and mangle table
  command: "iptables -t {{ item }} -F"
  loop:
    - "nat"
    - "mangle"

- name: Delete tables
  command: "iptables -X"

- name: Delete nat and mangle tables
  command: "iptables -t {{ item }} -X"
  loop:
    - "nat"
    - "mangle"

# - name: Iptables flush 
#   ansible.builtin.iptables:
#     chain: '{{ item }}'
#     flush: yes
#   with_items: [ 'INPUT', 'OUTPUT']

# - name: Iptables flush nat
#   ansible.builtin.iptables:
#     table: nat
#     chain: '{{ item }}'
#     flush: yes
#   with_items: [ 'INPUT', 'OUTPUT', 'PREROUTING', 'POSTROUTING' ]

# - name: Iptables flush mangle
#   ansible.builtin.iptables:
#     table: mangle
#     chain: '{{ item }}'
#     flush: yes
#   with_items: [ 'INPUT', 'OUTPUT', 'PREROUTING', 'POSTROUTING' ]
  
# - name: delete 
#   command: iptables -X

# - name: delete
#   command: iptables -t nat -X

# - name: delete
#   command: iptables -t mangle -X
  
# - iptables:
#     chain: mangle
#     chain_management: true
#     state: absent

# - iptables:
#     chain: nat
#     chain_management: true
#     state: absent

- name: IP tables rules 1
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: ens160
    jump: ACCEPT

- name: IP tables rules 2
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: ens192
    jump: MASQUERADE

- name: Enable ip forwarding 1
  ansible.builtin.blockinfile:
     path: /etc/sysctl.conf
     block: |
      net.ipv4.ip_forward = 1
     insertafter: EOF
     create: yes

- name: Enable ip forwarding 2
  ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes

- name: save ip forwarding 1
  command: sudo sysctl -p

- name: save iptables
  command: iptables-save
  become: true
  
- name: restart iptables
  command: service iptables restart

- name: restart conn
  command: nmcli connection reload && nmcli connection up ens160 && ifup ens160 

- name: systemctl start iptables
  command: systemctl start iptables
